### ISSUE TITLE
docker-compose.yml文件中有些配置不是很明白

### ISSUE THREAD

**Issue by Seameee** [JumpAlang/Jusic-Serve-Houses#43]
![PixPin_2024-08-08_23-39-01](https://github.com/user-attachments/assets/0fbc6e97-5284-448a-ac2c-4c66a91a6407)
你好，我在尝试使用提供的docker-compose.yml文件时遇到了一些问题，希望能得到解答，主要是部分环境变量与readme文件中的描述不符

1. "APIUSER"  "APIPWD"，这两个变量似乎是给basic认证使用的，我尝试删除两个变量或者变量内容写空，会导致后端报错后无限重启，如果保留两个变量就会在打开网站时显示需要basic登录认证
2. "RoleRootPassword"，这个变量不知道作用是什么，我删除掉这一项也没有引起什么错误
3.  "PlaylistSize" "ForeverlistSize"，这两个看变量名应该是显示的播放列表和我喜欢列表的数量或者歌单内歌曲的数量，希望能重新标注一下变量配置要求或者注释
4. "QqMusicGuid"，这个变量我在cookies里没有找到，辛苦给说明一下需要如何配置，还是保持默认即可

以下是我配置使用的docker-compose.yml文件内容：

```
version: "3"
services:
  service_redis:
    restart: always
    #    ports:
    #      - 6379:6379
    image: redis
    container_name: redis
    environment:
      - TZ=Asia/Shanghai
    command: redis-server
    volumes:
      - /root/MusicParty/data:/data  #redis数据挂载到本地
  service_jusicMusicApi:
    image: jumpalang/jusic_music_api:2.0
    environment:
      - QQ=123456789 #qq号
    container_name: jusicMusicApi
    ports:
    #  - "3000:3000"
      - "3300:3300"
    #      - "3400:3400"
    #      - "8081:8081"
    restart: always
  service_jusicServeHouses:
    container_name: jusicServeHouses
    image: jumpalang/jusic_serve_houses:4.9
    environment:
      - MusicApi=http://jusicMusicApi  #必须与service_jusicMusicApi的container_name一致
      - APIUSER=admin  #api认证接口用户名
      - APIPWD=123
      - WyAccount=xxxxxx@163.com
      - WyPassword=xxxxxx
      - PlaylistSize=23
      - ForeverlistSize=66
      - ReTryCount=2
      - RedisHost=redis
      - QqUin=123456789
      - QqMusicKey=Q_H_L_63k3NK0dL_E8tMfY4AGSBZrt4G323…
      - QqMusicGuid=114514
      - QqCdnAddr=http://ws.stream.qqmusic.qq.com/
      - QqRefreshInterval=86000000
      - HouseSize=5
      - IpHouse=1
    ports:
      - "8081:8888"
    depends_on:
      - service_redis
      - service_jusicMusicApi
    restart: always
```
