### ISSUE TITLE
如何查询application.yml中音乐相关配置项

### ISSUE THREAD

**Issue by YuLong-Liang** [JumpAlang/Jusic-Serve-Houses#48]
参考 Readme的安装部分，配置好QQ音乐的基础环境后，
Readme中描述在 src\main\resources\application.yml 中配置好 redis 以及音乐服务，
```yaml
  qq_uin: ${QqUin:1040927107}
  qq_music_key: ${QqMusicKey:Q_H_L_63k3NWYfBRq1KV0rBZ4ySa7vYK6XS5803Q23v35s4abc0rela9BzP6jBXv5Fgk9hsk4FLXXXXXX} #qq音乐cookie找到qqMusicKey,需要会员
  qq_music_guid: ${QqMusicGuid:114514}
  qq_cdn_addr: ${QqCdnAddr:http://ws.stream.qqmusic.qq.com/}
  qq_refresh_interval: ${QqRefreshInterval:86000000} #毫秒
```
这些内容应该在哪里查看？
